data_dir: "./data/FFHQ_testingsubset/"
output_dir: "./output/FFHQ_testingsubset/"
batch_size: 10
grad_accumulation: 1
overfit: true
validation_split: 0.0

model:
  num_gaussians: 1000
  input_dim: 8
  model_dim: 512

train:
  max_epochs: 2000

  base_lr: 0.0005      # 5e-5
  lr_warmup_epochs: 100

  target_recon_weight: 1.0

  target_kl_weight: 0.001
  kl_warmup_epochs: 200

  sinkhorn_warmup_epochs: 200
  clip_norm: 2.5

logging:
  sample_save_rate: 200
  reconstruct_save_rate: 10